services:
  node-exporter-new:
    image: prom/node-exporter:latest
    container_name: node-exporter-new
    restart: unless-stopped
    # Режим host позволяет контейнеру видеть реальные сетевые интерфейсы ноута
    network_mode: host
    # Позволяет видеть процессы хостовой системы
    pid: host
    volumes:
      # Пробрасываем корень системы хоста внутрь контейнера (только для чтения)
      - /:/host:ro,rslave
    command:
      # Указываем экспортеру, где искать данные о системе
      - '--path.rootfs=/host'
    deploy:
      resources:
        limits:
          memory: 50M # Жесткий лимит, чтобы не "съесть" твою память
